### PR TITLE
ACM-3275 Update format of trigger function

### PR DESCRIPTION
**Pull request by jlpadilla**
Signed-off-by: Jorge Padilla <jpadilla@redhat.com>

**Related Issue:**  ACM-3275

### Description of changes
- Replace tabs with spaces for nicer formatting of the yaml.

### BEFORE:
image

### AFTER:
image

### CODE REVIEW

**Review by SherinV — APPROVED** [review]

**Comment by jlpadilla** [comment]
Verified on dev cluster.

image

**Comment by jlpadilla** [comment]
image

**Pull request merged**
