### PR TITLE
remove readonly file system context for postgres

### PR DESCRIPTION
**Pull request by SherinV**
Signed-off-by: Sherin Varughese <shvarugh@redhat.com>

**Related Issue:**  stolostron/backlog#<ISSUE_NUMBER>

### Description of changes
Make postgres file system writable.

### CODE REVIEW

**Review by xrajesh — APPROVED** [review]

**Comment by SherinV** [comment]
Overriding the sonar cloud bug of the postgres function > 120 lines of code. It is only 1 line above the limit and it helps maintain consistency with other deployment files.
/override ci/prow/sonar-pre-submit

**Review by jlpadilla — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
